addpath("D:\NYNGroup\eeglab2023.1\")
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Generate PPvalidation .set data (preprocessed)
% CONFIGURATION VARIABLES
type_of_pp  = 'pp01';
dataPath    = 'D:\shared_git\MaestriaThesis\NeuroSenseDatabase';
ggERP       = true;                    
PSD         = false;
ERSP_ITPC   = false;
DipClus     = true;
savejpg     = true;
savemat     = true;
saveStudy   = true;
recompute = true;
plot_clustmetrics = true;
StudyInfo  = {};
outPath    =  fullfile('D:\shared_git\MaestriaThesis\results', type_of_pp, 'eeglabStudy');
listStimuli = {'Air','Air1','Air2','Air3','Air4',...
               'Vib','Vib1','Vib2','Vib3','Vib4',...
               'Car','Car1','Car2','Car3','Car4'};
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for type = [5,10,15]
    tstimul = listStimuli{type};
    StudyInfo = getStudyInfo(dataPath,tstimul,type_of_pp);
    DataStruct = getDataFromStudy(StudyInfo, type_of_pp, tstimul ...
    ,'ggERP'       , ggERP ... 
    ,'PSD'         , PSD ...
    ,'ERSP_ITPC'   , ERSP_ITPC ...
    ,'DipClus'     , DipClus ...
    ,'savejpg'     , savejpg...
    ,'savemat'     , savemat...
    ,'fignum'      , type ...
    ,'recompute'   , recompute ...
    ,'saveStudy'   , saveStudy ...
    ,'plot_clustmetrics', plot_clustmetrics...
    ,'numclust', 12);
     %'outPath'     , outPath ...
end
